import { useState, useEffect } from "react";

export default function FilterPopup({ onClose, onApplyFilters }) {
  const [range, setRange] = useState(0);
  const [selectedIndustry, setSelectedIndustry] = useState("");
  const [selectedCategory, setSelectedCategory] = useState("");
  // 👇 this defines index so it exists
  const [index, setIndex] = useState(0);

  // Industry list
  // const industries = [
  //   "Automotive",
  //   "Beauty & Spas",
  //   "Children's Businesses",
  //   "Education",
  //   "Entertainment",
  //   "Fitness",
  //   "Food & Beverage",
  //   "Home Services",
  //   "Lodging",
  //   "Medical",
  //   "Pets",
  //   "Professional Services",
  //   "Retail",
  // ];

  // Subcategories for each industry
  // const subcategories = {
  //   Automotive: [
  //     "Auto Customization",
  //     "Auto Detailing",
  //     "Auto Glass Services",
  //     "Auto Parts & Supplies",
  //     "Auto Rental",
  //     "Auto Repair",
  //     "Auto Tag Agency",
  //     "Body Shops",
  //     "Car Brokers",
  //     "Car Dealers",
  //     "Car Wash",
  //     "Car Window Tinting",
  //     "Exotic Car Rental",
  //     "Gas Stations",
  //     "Mobile Dent Repair",
  //     "Oil Change",
  //     "Powdercoating",
  //     "Tire Change",
  //     "Tire Shop",
  //     "Towing",
  //     "Trailer Rental",
  //     "Transmission Repair",
  //     "Used Car Dealers",
  //     "Vehicle Wraps",
  //     "Waterless Car Wash",
  //     "Wheel & Rim Repair",
  //     "Wheels & Tire Shop",
  //     "Windshield Installation & Repair",
  //   ],
  //   "Beauty & Spas": [
  //     "Acne Treatment",
  //     "Barbershop",
  //     "Body Contouring",
  //     "Blow Dry/Out Services",
  //     "Day Spas",
  //     "Eyebrows",
  //     "Eyelashes",
  //     "Facial Spa",
  //     "Foot Care",
  //     "Hair Extensions",
  //     "Hair Loss Centers",
  //     "Hair Removal",
  //     "Hair Salon",
  //     "Kids Hair Salon",
  //     "Laser Hair Removal",
  //     "Makeup Artists",
  //     "Massage",
  //     "Medical Spa",
  //     "Men’s Hair Salon",
  //     "Men's Grooming",
  //     "Nail Salons",
  //     "Permanent Makeup",
  //     "Piercing",
  //     "Skin Care",
  //     "Sugaring",
  //     "Salon Suites",
  //     "Tanning",
  //     "Tattoo",
  //     "Teeth Whitening",
  //     "Threading",
  //     "Waxing",
  //     "Tattoo Removal",
  //   ],
  //   "Children's Businesses": [
  //     "After School Program",
  //     "Basketball Lessons",
  //     "Child Care",
  //     "Day Care",
  //     "Entertainment Center",
  //     "Event Planning",
  //     "Face Painting",
  //     "Music Lessons",
  //     "Nanny Care",
  //     "Party Rental",
  //     "Soccer Lessons",
  //     "Summer Camps",
  //     "Tennis Lessons",
  //     "Tutoring Center",
  //   ],
  //   Education: [
  //     "Art Classes",
  //     "Bartending School",
  //     "Cheese Tasting Classes",
  //     "Art School",
  //     "Children's Tutoring",
  //     "College Counseling",
  //     "Cooking Schools",
  //     "Cosmetology School",
  //     "Dance Schools",
  //     "Driving Schools",
  //     "Educational Services",
  //     "Firearm Training",
  //     "Language School",
  //     "Montessori School",
  //     "Pole Dancing Classes",
  //     "Preschool",
  //     "Private Tutoring",
  //     "Specialty School",
  //     "Speech Training",
  //     "Swimming Lessons",
  //     "Tasting Classes",
  //     "Test Preparation",
  //     "Tutoring Center",
  //     "Wine Tasting Classes",
  //   ],
  //   Entertainment: [
  //     "Arcade",
  //     "Archery",
  //     "Axe Throwing",
  //     "Batting Cages",
  //     "Bowling",
  //     "Challenge Courses",
  //     "Climbing",
  //     "Comedy Club",
  //     "Drive In Movie Theater",
  //     "Escape Games",
  //     "Event Planning",
  //     "Festival",
  //     "Golf Simulator",
  //     "Haunted House",
  //     "Laser Tag",
  //     "Mini Golf",
  //     "Movie Theater",
  //     "Night Club",
  //     "Ninja Park",
  //     "Obstacle Courses",
  //     "Paint + Sip",
  //     "Paintball",
  //     "Party Rental",
  //     "Photo Booths",
  //     "Pickle Ball",
  //     "Pool Hall",
  //     "Race Tracks",
  //     "Skating Rink",
  //     "Sky Diving",
  //     "Smash Room",
  //     "Strip Club",
  //     "Trampoline Park",
  //     "Trivia Games",
  //     "Virtual Reality Centers",
  //   ],
  //   Fitness: [
  //     "Aerial Fitness",
  //     "Barre Fitness",
  //     "Batting Cages",
  //     "Big Box Gym",
  //     "Boot Camp",
  //     "Boxing Gym",
  //     "Cardio Classes",
  //     "Children's Fitness",
  //     "Circuit Training Gym",
  //     "Cycling Studio",
  //     "Dance Studio",
  //     "Elderly Fitness",
  //     "Fitness Studio",
  //     "Gym",
  //     "Health Club",
  //     "Hiit Studio",
  //     "Hot Yoga Studio",
  //     "Interval Training Gym",
  //     "Jiu Jitsu Studio",
  //     "Karate",
  //     "Kickboxing Gym",
  //     "Martial Arts",
  //     "Mixed Martial Arts",
  //     "Mobile Gym",
  //     "Muy Thai",
  //     "Ninja Gym",
  //     "Personal Training",
  //     "Pilates Studio",
  //     "Rowing Studio",
  //     "Running",
  //     "Sauna Studio",
  //     "Self Defense Classes",
  //     "Spinning Studio",
  //     "Stretch Studio",
  //     "Women's Gym",
  //     "Yoga Studio",
  //   ],
  //   "Food & Beverage": [
  //     "Acai",
  //     "African Cuisine",
  //     "Argentinean",
  //     "Asian",
  //     "Bagel Shop",
  //     "Bakeries",
  //     "Bar",
  //     "Barbecue",
  //     "BBQ Joint",
  //     "Bistro Café",
  //     "Boba Shop",
  //     "Brazilian",
  //     "Brazilian Steakhouse",
  //     "Breakfast",
  //     "Brewery",
  //     "Bubble Tea",
  //     "Burger Joint",
  //     "Burgers",
  //     "Café",
  //     "Café",
  //     "Cafeteria",
  //     "Cajun",
  //     "Cajun Boil",
  //     "Cake Shop",
  //     "Carribean",
  //     "Cereal Bar",
  //     "Cheesteaks",
  //     "Chicken Shop",
  //     "Chicken Wings",
  //     "Chimney Cakes",
  //     "Chinese Food",
  //     "Chocolate Shop",
  //     "Churros",
  //     "Coffee & Tea",
  //     "Coffee Shop",
  //     "Colombian",
  //     "Comfort Food",
  //     "Convenience Store",
  //     "Cookies",
  //     "Creole",
  //     "Creperie",
  //     "Cuban",
  //     "Cupcakes",
  //     "Custom Cakes",
  //     "Delicatessen",
  //     "Dessert Shop",
  //     "Dim Sum",
  //     "Diner",
  //     "Donut Shop",
  //     "Ethical Grocery Store",
  //     "Farmers Market",
  //     "Filipino",
  //     "Fish Fry",
  //     "Focaccia Sandwich Shop",
  //     "Fondue",
  //     "Food Delivery Service",
  //     "French",
  //     "French Fry Bar",
  //     "Gelato",
  //     "German",
  //     "Haitian",
  //     "Halal",
  //     "Hawaiian",
  //     "Health Market",
  //     "Honduran",
  //     "Hot Dogs",
  //     "Hot Pot",
  //     "Ice Cream",
  //     "Ice Cream & Frozen Yogurt",
  //     "Indian Food",
  //     "Internet Café",
  //     "Israeli",
  //     "Italian",
  //     "Japanese",
  //     "Jewish Deli",
  //     "Juice Bar",
  //     "Juice Bar & Smoothies",
  //     "Kebabs",
  //     "Korean",
  //     "Korean BBQ",
  //     "Kosher",
  //     "Latin American",
  //     "Lounge",
  //     "Macarons",
  //     "Meat Shop",
  //     "Mediterranean",
  //     "Mexican",
  //     "Middle Eastern",
  //     "Milk Bars",
  //     "Milkshake Bar",
  //     "Nicaraguan",
  //     "Nitrogen Ice Cream",
  //     "Noodles",
  //     "Organic Store",
  //     "Paella",
  //     "Paella & Tapas",
  //     "Pakistani",
  //     "Pasta",
  //     "Persian",
  //     "Pita",
  //     "Pizza",
  //     "Poke",
  //     "Polish",
  //     "Polynesian",
  //     "Pretzels",
  //     "Pub",
  //     "Ramen",
  //     "Seafood",
  //     "Shaved Ice",
  //     "Smoothie Shop",
  //     "Soul Food",
  //     "Spanish",
  //     "Specialty Shop",
  //     "Sports Bar",
  //     "Steakhouse",
  //     "Street Vendor",
  //     "Sub Sandwiches",
  //     "Sushi",
  //     "Sushi Bar",
  //     "Sushi Conveyor Belt",
  //     "Taco Joint",
  //     "Tacos",
  //     "Tapas Bar",
  //     "Tea Room",
  //     "Tex Mex",
  //     "Thai",
  //     "Turkish",
  //     "Udon",
  //     "Vegan",
  //     "Vegetarian",
  //     "Venezuelan",
  //     "Vietnamese",
  //     "Wine Bar",
  //     "Wine Tasting Room",
  //     "Wok",
  //     "Wraps",
  //   ],
  //   "Home Services": [
  //     "Air Duct Cleaning",
  //     "Appliances & Repair",
  //     "Artificial Turf",
  //     "Awnings",
  //     "Cabinetry",
  //     "Carpet Cleaning",
  //     "Childproofing",
  //     "Contractors",
  //     "Custom Closets",
  //     "Damage Restoration",
  //     "Decks & Railing",
  //     "Drywall Installation & Repair",
  //     "Dumpster Rental",
  //     "Electricians",
  //     "Fences & Gates",
  //     "Fire Protection",
  //     "Flooring",
  //     "Garage Door Repair",
  //     "Glass Cleaning",
  //     "Grout Services",
  //     "Gutter Services",
  //     "Handyman",
  //     "Hazardous Waste Disposal",
  //     "Heating & Air Conditioning/HVAC",
  //     "Holiday Decorating Services",
  //     "Home Automation",
  //     "Home Cleaning",
  //     "Home Inspectors",
  //     "Home Network Installation",
  //     "Home Staging",
  //     "Home Theatre Installation",
  //     "Home Window Tinting",
  //     "HVAC Service",
  //     "Insulation Installation",
  //     "Interior Design",
  //     "Irrigation",
  //     "Junk Removal & Hauling",
  //     "Keys & Locksmiths",
  //     "Lawn Services",
  //     "Lighting Fixtures & Equipment",
  //     "Marble Restoration",
  //     "Mobile Home Repair",
  //     "Mold Remdiation Service",
  //     "Moving Service",
  //     "Painting Service",
  //     "Pest Control Service",
  //     "Plumbing",
  //     "Pool & Hot Tub Service",
  //     "Pool Cleaners",
  //     "Pressure Washers",
  //     "Property Management",
  //     "Residential Cleaning",
  //     "Roofing",
  //     "Security Systems",
  //     "Self Storage Service",
  //     "Shades & Blinds",
  //     "Shutters",
  //     "Solar Installation",
  //     "Solar Panel Cleaning",
  //     "Storage Container Company",
  //     "Stucco Service",
  //     "Tile + Grout Restoration",
  //     "Tree Service",
  //     "TV Mounting Service",
  //     "Wildlife Control",
  //     "Window Cleaning Service",
  //     "Windows + Doors Installation",
  //   ],
  //   Lodging: [
  //     "Bed & Breakfast",
  //     "Boutique Hotel",
  //     "Eco Lodge",
  //     "Glamping",
  //     "Hostel",
  //     "Hotel",
  //     "Motel",
  //     "RV Park",
  //     "Vacation Rentals",
  //   ],
  //   Medical: [
  //     "ABA Therapy Practice",
  //     "Acupuncture Practice",
  //     "Addiction Recovery Center",
  //     "Alternative Medicine",
  //     "Assisted Living Facility",
  //     "Audiology Practice",
  //     "Behavioral Health Care",
  //     "Cannabis Clinic",
  //     "Cardiology",
  //     "Chiropractor",
  //     "Colonics",
  //     "Concierge Medical Practice",
  //     "Cosmetic Dentistry",
  //     "Cosmetic Surgeons",
  //     "Counseling & Mental Health",
  //     "Cryotherapy",
  //     "Dentistry Practice",
  //     "Dermatology Practice",
  //     "Detox Clinic",
  //     "Diagnostic Imaging",
  //     "Drug Testing Lab",
  //     "Eyecare",
  //     "Family Practice",
  //     "General Dentistry Practice",
  //     "Hair Loss Clinic",
  //     "Hearing Aids",
  //     "Home Health Care",
  //     "Hyperbaric Chamber",
  //     "Laboratory Testing",
  //     "Medical Billing",
  //     "Medical Marijuana Center",
  //     "Medical Nail Salon",
  //     "Medical Spa",
  //     "Mental Health Clinic",
  //     "Mobile Clinic",
  //     "Naturopathic/Holistic Care",
  //     "Optical",
  //     "Oxygen Bar",
  //     "Pain Management Clinic",
  //     "Pediatric Dentists",
  //     "Pediatric Practice",
  //     "Physical Therapy Practice",
  //     "Plastic Surgery Center",
  //     "Preventive Medicine",
  //     "Psychiatry Practice",
  //     "Psychology Practice",
  //     "Senior Care",
  //     "Sex Therapy Clinic",
  //     "Skilled Nursing",
  //     "Sleep Clinic",
  //     "Sports Medicine",
  //     "Stretch Studio",
  //     "Tattoo Removal Studio",
  //     "Urgent Care Center",
  //     "Walk In Clinic",
  //     "Weight Loss Clinic",
  //     "Weightloss",
  //     "Wound Care",
  //   ],
  //   Pets: [
  //     "Animal Physical Therapy",
  //     "Dog Walkers",
  //     "Emergency Pet Hospital",
  //     "Mobile Pet Grooming",
  //     "Pet Groomers",
  //     "Pet Hotel",
  //     "Pet Salon",
  //     "Pet Services",
  //     "Pet Sitting",
  //     "Pet Stores",
  //     "Pet Training",
  //     "Pet Transportation",
  //     "Pet Waste Removal",
  //     "Poop Cleaning",
  //     "Veterinarians",
  //     "Wildlife Removal",
  //   ],
  //   "Professional Services": [
  //     "Accident Assistance",
  //     "Accountanting Firm",
  //     "Architectural Firm",
  //     "Boat Repair",
  //     "Bookkeepers",
  //     "Business Brokers",
  //     "Business Consulting",
  //     "Commerical Cleaning",
  //     "Credit Repair",
  //     "Debt Repair",
  //     "Executive Offices",
  //     "Insurance",
  //     "IT Services",
  //     "Law Practice",
  //     "Life Coach",
  //     "Marketing Agency",
  //     "Matchmakers",
  //     "Office Cleaning",
  //     "Powdercoating",
  //     "Power Washing",
  //     "Private Investigation",
  //     "Process Server",
  //     "Property Management",
  //     "Public Adjusting Firm",
  //     "Real Estate",
  //     "Security Services",
  //     "Shared Office Space",
  //     "Shredding Services",
  //     "Signs",
  //     "Staffing Services",
  //     "Tax Preparation",
  //     "Title Company",
  //     "Travel Agency",
  //   ],
  //   Retail: [
  //     "Accessories Store",
  //     "Adult Store",
  //     "Appliance Store",
  //     "Arts & Crafts Store",
  //     "Baby Store",
  //     "Battery Store",
  //     "Bespoke Clothing Store",
  //     "Bike Store",
  //     "Book Store",
  //     "Bridal Store",
  //     "Candle Stores",
  //     "Cannabis Dispensary",
  //     "Check Cashing Store",
  //     "Children’s Clothing Store",
  //     "Christmas Trees",
  //     "Clothing Rental",
  //     "Computer Store",
  //     "Consignment Store",
  //     "Convenience Store",
  //     "Cosmetics & Beauty Supply Store",
  //     "Costume Store",
  //     "Dance Wear",
  //     "Discount Store",
  //     "Drone Store",
  //     "Dry Cleaner",
  //     "Electronics Store",
  //     "Executive Offices",
  //     "Eyewear Store",
  //     "Fashion Store",
  //     "Fireworks Store",
  //     "Fitness/Exercise Equipment Store",
  //     "Florist",
  //     "Flowers & Gifts Store",
  //     "Formal Wear Store",
  //     "Framing Store",
  //     "Furniture Store",
  //     "Garden Store",
  //     "Gift Shop",
  //     "Gold Buyers",
  //     "Golf Equipment Store",
  //     "Grocery Store",
  //     "Guns & Ammo Store",
  //     "Hardware Store",
  //     "Head Shop",
  //     "Hobby Shop",
  //     "Holiday Decorations",
  //     "Home & Garden Store",
  //     "Home Decor",
  //     "Hookah Bar",
  //     "Hot Tub & Pool Store",
  //     "Hunting & Fishing Store",
  //     "Jewelry Store",
  //     "Kitchen & Bath Store",
  //     "Laundromat",
  //     "Leather Goods Store",
  //     "Lighting Store",
  //     "Lingerie Store",
  //     "Luggage Store",
  //     "Mailbox Center",
  //     "Mattress Store",
  //     "Medical Supplies Store",
  //     "Men’s Clothing Store",
  //     "Military Surplus Store",
  //     "Mobile Phone Accessories Store",
  //     "Mobile Phone Store",
  //     "Office Equipment Store",
  //     "Organic Store",
  //     "Outdoor Furniture Store",
  //     "Outdoor Gear",
  //     "Outlet Stores",
  //     "Paint Store",
  //     "Paintball Store",
  //     "Pawn Shop",
  //     "Perfume Store",
  //     "Pharmacy",
  //     "Plus Size Fashion Store",
  //     "Pop-up Shop",
  //     "Print Shop",
  //     "Pumpkin Patches",
  //     "Rug Stores",
  //     "Self Storage",
  //     "Shared Office Spaces",
  //     "Sheds Store",
  //     "Shoe Stores",
  //     "Skate Shop",
  //     "Ski & Snowboard Shop",
  //     "Sneaker Store",
  //     "Souvenir Shop",
  //     "Spiritual Shop",
  //     "Sporting Goods Store",
  //     "Sporting Goods Store",
  //     "Storage Facility",
  //     "Sunglass Store",
  //     "Surf Shop",
  //     "Swimwear Store",
  //     "Thrift Store",
  //     "Tobacco Shop",
  //     "Toy Stores",
  //     "Traditional Clothing Store",
  //     "Trophy Shop",
  //     "Uniform Store",
  //     "Vape Shop",
  //     "Video Game Store",
  //     "Vitamins & Supplements Store",
  //     "Wholesale Store",
  //     "Wigs Store",
  //     "Women’s Clothing Store",
  //   ],
  // };

  const industries = [
    "Other",
    "Supplies",
    "Repair & Maintenance",
    "Gas Station",
    "Rentals",
    "Car Wash",
    "Salon",
    "Marketing",
    "Accounting & Insurance",
    "Staffing & Personnel",
    "Professional Networking",
    "Sports & Recreation",
    "Supplemental & Remedial Learning",
    "School",
    "Fitness Center",
    "Boutique",
    "Sports",
    "Home & Senior Care",
    "Maintenance, Repair, & Restoration",
    "Commercial Cleaning",
    "Pest Control",
    "Landscaping",
    "Residential Cleaning",
    "Junk Removal",
    "Online & Technology",
    "Brokerage",
    "Property Management",
    "Coworking & Workspaces",
    "Fast Casual",
    "Desserts",
    "Coffee, Tea, & Drinks",
    "Full-Service",
    "Quick Service",
    "Cannabis",
    "Resales",
    "Hotels & Lodging",
  ];

  const subcategories = [
    "Automotive & Boat",
    "Beauty & Personal Care",
    "Business & Professional Services",
    "Education & Children",
    "Fitness",
    "Healthcare",
    "Home & Building Services",
    "Other Businesses",
    "Pets",
    "Real Estate",
    "Restaurants & Food",
    "Retail",
    "Travel & Hospitality",
  ];

  const handleApply = () => {
    const filters = {
      industry: selectedIndustry,
      category: selectedCategory,
    };
    onApplyFilters(filters);
    onClose();
  };

  const handleClear = () => {
    setSelectedIndustry("");
    setSelectedCategory("");
    setSelectedPriceRange("");
    onApplyFilters({ industry: "", category: "", priceRange: "" });
    onClose();
  };

  const ranges = [
    "Under $50,000",
    "$50,000 - $99,999",
    "$100,000 - $249,999",
    "$250,000 - $499,999",
    "$500,000 - $999,999",
    "$1 Million and up",
  ];

  useEffect(() => {
    const input = document.getElementById("rangeSlider");
    if (input) {
      updateSliderBackground(input);
    }
  }, [index]);

  const updateSliderBackground = (input) => {
    const min = parseInt(input.min);
    const max = parseInt(input.max);
    const val = parseInt(input.value);

    const percentage = ((val - min) / (max - min)) * 100;

    input.style.background = `linear-gradient(to right, #00db75 0%, #00b4db ${percentage}%, #ddd ${percentage}%)`;
  };

  return (
    <div className="">
      <div className="bg-white rounded-2xl p-6 shadow-xl border">
        <h4 className="font-semibold mb-6 text-start apply_filter">
          Apply Filters
        </h4>

        {/* Industry & Category */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
          <select
            className="w-full border border-gray-300 rounded-md filter-select-tab text-sm text-gray-700 focus:outline-none focus:ring-2 focus:ring-blue-500"
            value={selectedIndustry}
            onChange={(e) => {
              setSelectedIndustry(e.target.value);
              // reset category
            }}
          >
            <option value="">Select Industry</option>
            {industries.map((ind, index) => (
              <option key={index} value={ind}>
                {ind}
              </option>
            ))}
          </select>

          <select
            className="w-full border border-gray-300 rounded-md filter-select-tab text-sm text-gray-700 focus:outline-none focus:ring-2 focus:ring-blue-500"
            value={selectedCategory}
            onChange={(e) => setSelectedCategory(e.target.value)}
            disabled={!selectedIndustry}
          >
            <option value="">Select Category</option>
            {subcategories.map((subcat, index) => (
              <option key={index} value={subcat}>
                {subcat}
              </option>
            ))}
          </select>
        </div>

        <div className="mb-6 text-start">
          <label className="block text-sm mb-2  price-range-label">
            Investment Range:{" "}
            <span className="font-bold price-range-amt">{ranges[index]}</span>
          </label>

          <input
            id="rangeSlider"
            type="range"
            min={0}
            max={ranges.length - 1}
            step={1}
            value={index}
            onChange={(e) => setIndex(Number(e.target.value))}
            className="w-full price-range"
          />
        </div>

        {/* Buttons */}
        <div className="flex justify-end gap-3">
          <button onClick={handleClear} className=" clear-all-btn">
            Clear All
          </button>
          <button
            onClick={handleApply}
            className="Applyfilter-btn apply-filter-btn"
          >
            Apply
          </button>
        </div>
      </div>
    </div>
  );
}
